name: "Terraform Action"
description: "Install, setup, and run Terraform init."
inputs:
  working-directory:
    description: "Working directory for Terraform to initialize."
    required: true
runs:
  using: composite
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    - name: Run Terraform Init
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
