name: "Terraform Plan"
on:
  workflow_call:
    inputs:
      gcp-wif-project-number:
        description: "GCP Workload Identity Federation project number."
        required: true
      pool-id:
        description: "GCP Workload Identity Federation Pool ID."
        required: true
      provider-id:
        description: "GCP Workload Identity Federation Provider ID."
        required: true
      working-directory:
        description: "Working directory for Terraform to initialize."
        required: true
      gcp-project-id:
        description: "GCP project ID."
        required: true
    secrets:
      gcp-service-account-email:
        description: "GCP service account email for use with Terraform."
        required: true
jobs:
  terraform-plan:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Setup Github Actions checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ inputs.gcp-wif-project-number }}/locations/global/workloadIdentityPools/${{ inputs.pool-id }}/providers/${{ inputs.provider-id }}'
          service_account: '${{ secrets.gcp-service-account-email }}'
      - name: Terraform init
        uses: asison19/github-actions/composite-actions/terraform-action@v1.1.2
        with:
          working-directory: ${{ inputs.working-directory }}
      - name: Run Terraform Plan
        run: terraform plan
        working-directory: ${{ inputs.working-directory }}
        env:
          TF_VAR_GCP_PROJECT_ID: ${{ inputs.gcp-project-id }}
